import type { Formation } from './types';

// y: 0 = own goal line, 100 = opposition goal. Rendered bottom-to-top.
export const FORMATIONS: Formation[] = [
    {
        id: '4-3-3',
        name: '4-3-3',
        bonus: 1.02,
        slots: [
            { id: 'gk', label: 'GK', accepts: ['GK'], x: 50, y: 6 },
            { id: 'lb', label: 'LB', accepts: ['LB', 'CB'], x: 14, y: 26 },
            { id: 'cb1', label: 'CB', accepts: ['CB', 'CDM'], x: 38, y: 22 },
            { id: 'cb2', label: 'CB', accepts: ['CB', 'CDM'], x: 62, y: 22 },
            { id: 'rb', label: 'RB', accepts: ['RB', 'CB'], x: 86, y: 26 },
            { id: 'cm1', label: 'CM', accepts: ['CM', 'CDM', 'CAM'], x: 28, y: 50 },
            { id: 'cm2', label: 'CM', accepts: ['CM', 'CDM', 'CAM'], x: 50, y: 46 },
            { id: 'cm3', label: 'CM', accepts: ['CM', 'CDM', 'CAM'], x: 72, y: 50 },
            { id: 'lw', label: 'LW', accepts: ['LW', 'RW', 'ST', 'CAM'], x: 16, y: 78 },
            { id: 'st', label: 'ST', accepts: ['ST', 'CAM'], x: 50, y: 84 },
            { id: 'rw', label: 'RW', accepts: ['RW', 'LW', 'ST', 'CAM'], x: 84, y: 78 },
        ],
    },
    {
        id: '4-4-2',
        name: '4-4-2',
        bonus: 1.0,
        slots: [
            { id: 'gk', label: 'GK', accepts: ['GK'], x: 50, y: 6 },
            { id: 'lb', label: 'LB', accepts: ['LB', 'CB'], x: 14, y: 26 },
            { id: 'cb1', label: 'CB', accepts: ['CB', 'CDM'], x: 38, y: 22 },
            { id: 'cb2', label: 'CB', accepts: ['CB', 'CDM'], x: 62, y: 22 },
            { id: 'rb', label: 'RB', accepts: ['RB', 'CB'], x: 86, y: 26 },
            { id: 'lm', label: 'LM', accepts: ['LW', 'CM', 'CAM'], x: 14, y: 54 },
            { id: 'cm1', label: 'CM', accepts: ['CM', 'CDM', 'CAM'], x: 38, y: 50 },
            { id: 'cm2', label: 'CM', accepts: ['CM', 'CDM', 'CAM'], x: 62, y: 50 },
            { id: 'rm', label: 'RM', accepts: ['RW', 'CM', 'CAM'], x: 86, y: 54 },
            { id: 'st1', label: 'ST', accepts: ['ST', 'CAM'], x: 38, y: 82 },
            { id: 'st2', label: 'ST', accepts: ['ST', 'CAM'], x: 62, y: 82 },
        ],
    },
    {
        id: '4-2-3-1',
        name: '4-2-3-1',
        bonus: 1.01,
        slots: [
            { id: 'gk', label: 'GK', accepts: ['GK'], x: 50, y: 6 },
            { id: 'lb', label: 'LB', accepts: ['LB', 'CB'], x: 14, y: 26 },
            { id: 'cb1', label: 'CB', accepts: ['CB', 'CDM'], x: 38, y: 22 },
            { id: 'cb2', label: 'CB', accepts: ['CB', 'CDM'], x: 62, y: 22 },
            { id: 'rb', label: 'RB', accepts: ['RB', 'CB'], x: 86, y: 26 },
            { id: 'cdm1', label: 'CDM', accepts: ['CDM', 'CM', 'CB'], x: 38, y: 42 },
            { id: 'cdm2', label: 'CDM', accepts: ['CDM', 'CM', 'CB'], x: 62, y: 42 },
            { id: 'lw', label: 'LW', accepts: ['LW', 'RW', 'CAM'], x: 16, y: 64 },
            { id: 'cam', label: 'CAM', accepts: ['CAM', 'CM', 'ST'], x: 50, y: 62 },
            { id: 'rw', label: 'RW', accepts: ['RW', 'LW', 'CAM'], x: 84, y: 64 },
            { id: 'st', label: 'ST', accepts: ['ST', 'CAM'], x: 50, y: 86 },
        ],
    },
    {
        id: '3-5-2',
        name: '3-5-2',
        bonus: 1.01,
        slots: [
            { id: 'gk', label: 'GK', accepts: ['GK'], x: 50, y: 6 },
            { id: 'cb1', label: 'CB', accepts: ['CB', 'CDM'], x: 26, y: 22 },
            { id: 'cb2', label: 'CB', accepts: ['CB', 'CDM'], x: 50, y: 20 },
            { id: 'cb3', label: 'CB', accepts: ['CB', 'CDM'], x: 74, y: 22 },
            { id: 'lwb', label: 'LWB', accepts: ['LB', 'LW', 'CM'], x: 10, y: 48 },
            { id: 'cm1', label: 'CM', accepts: ['CM', 'CDM', 'CAM'], x: 32, y: 48 },
            { id: 'cm2', label: 'CM', accepts: ['CM', 'CDM', 'CAM'], x: 50, y: 44 },
            { id: 'cm3', label: 'CM', accepts: ['CM', 'CDM', 'CAM'], x: 68, y: 48 },
            { id: 'rwb', label: 'RWB', accepts: ['RB', 'RW', 'CM'], x: 90, y: 48 },
            { id: 'st1', label: 'ST', accepts: ['ST', 'CAM'], x: 38, y: 82 },
            { id: 'st2', label: 'ST', accepts: ['ST', 'CAM'], x: 62, y: 82 },
        ],
    },
    {
        id: '5-3-2',
        name: '5-3-2',
        bonus: 1.0,
        slots: [
            { id: 'gk', label: 'GK', accepts: ['GK'], x: 50, y: 6 },
            { id: 'lb', label: 'LB', accepts: ['LB', 'LW'], x: 10, y: 30 },
            { id: 'cb1', label: 'CB', accepts: ['CB', 'CDM'], x: 30, y: 22 },
            { id: 'cb2', label: 'CB', accepts: ['CB', 'CDM'], x: 50, y: 20 },
            { id: 'cb3', label: 'CB', accepts: ['CB', 'CDM'], x: 70, y: 22 },
            { id: 'rb', label: 'RB', accepts: ['RB', 'RW'], x: 90, y: 30 },
            { id: 'cm1', label: 'CM', accepts: ['CM', 'CDM', 'CAM'], x: 28, y: 52 },
            { id: 'cm2', label: 'CM', accepts: ['CM', 'CDM', 'CAM'], x: 50, y: 48 },
            { id: 'cm3', label: 'CM', accepts: ['CM', 'CDM', 'CAM'], x: 72, y: 52 },
            { id: 'st1', label: 'ST', accepts: ['ST', 'CAM'], x: 38, y: 82 },
            { id: 'st2', label: 'ST', accepts: ['ST', 'CAM'], x: 62, y: 82 },
        ],
    },
    {
        id: '4-5-1',
        name: '4-5-1',
        bonus: 1.0,
        slots: [
            { id: 'gk', label: 'GK', accepts: ['GK'], x: 50, y: 6 },
            { id: 'lb', label: 'LB', accepts: ['LB', 'CB'], x: 14, y: 26 },
            { id: 'cb1', label: 'CB', accepts: ['CB', 'CDM'], x: 38, y: 22 },
            { id: 'cb2', label: 'CB', accepts: ['CB', 'CDM'], x: 62, y: 22 },
            { id: 'rb', label: 'RB', accepts: ['RB', 'CB'], x: 86, y: 26 },
            { id: 'lm', label: 'LM', accepts: ['LW', 'CM'], x: 10, y: 54 },
            { id: 'cm1', label: 'CM', accepts: ['CM', 'CDM', 'CAM'], x: 32, y: 50 },
            { id: 'cm2', label: 'CM', accepts: ['CM', 'CDM', 'CAM'], x: 50, y: 46 },
            { id: 'cm3', label: 'CM', accepts: ['CM', 'CDM', 'CAM'], x: 68, y: 50 },
            { id: 'rm', label: 'RM', accepts: ['RW', 'CM'], x: 90, y: 54 },
            { id: 'st', label: 'ST', accepts: ['ST', 'CAM'], x: 50, y: 84 },
        ],
    },
];

export function getFormation(id: string): Formation {
    return FORMATIONS.find((f) => f.id === id) ?? FORMATIONS[0];
}
